# env
env: cheetah_run    # domain1 and downstream task
env_2: walker_run    # domain2
env_3: quadruped_run   # domain3
frame_stack: 3
action_repeat: 2
# train
num_train_steps: 350000 # 700k total env steps (200k random data steps (100k transitions) for pre-training and 500k steps for donwstream task)
num_expl_steps: 100000 # 100k random transitions (2 * 100000)
num_random_steps: 1000
replay_buffer_capacity: 100000  #random data buffer
replay_buffer_capacity_task: 40000    # donwstream RL buffer
seed: 1
# eval
eval_frequency: 5000
num_eval_episodes: 10
# misc
log_frequency_step: 10000
log_save_tb: true
save_video: true
save_model: true
save_buffer: false
save_pixels: false
save_frequency: 10000
device: 2

load_pretrained: false
pretrained_step: 250000
pretrained_dir: none


agent:
  class: proto.ProtoAgent
  name: CRPTpro
  params:
    obs_shape: ??? # to be specified later
    action_shape: ??? # to be specified later
    action_range: ??? # to be specified later
    device: ${device}
    encoder_cfg: ${encoder}
    critic_cfg: ${critic}
    actor_cfg: ${actor}
    proto_cfg: ${proto}
    discount: 0.99
    init_temperature: 0.1
    lr: 1e-4
    actor_update_frequency: 2
    critic_target_tau: 0.01
    critic_target_update_frequency: 2
    encoder_target_tau: 0.05
    encoder_update_frequency: 2
    batch_size: 512
    task_agnostic: ???
    intr_coef: 0.2
    num_seed_steps: 1000
    
critic:
  class: proto.Critic
  params:
    repr_dim: ???
    feature_dim: 50
    action_shape: ${agent.params.action_shape}
    hidden_dim: 1024
    hidden_depth: 2
    
actor:
  class: proto.Actor
  params:
    repr_dim: ???
    feature_dim: 50
    action_shape: ${agent.params.action_shape}
    hidden_depth: 2
    hidden_dim: 1024
    log_std_bounds: [-10, 2]
    
encoder:
  class: proto.Encoder
  params:
      obs_shape: ${agent.params.obs_shape}
      proj_dim: 128
        
proto:
  class: proto.Proto
  params:
      proj_dim: ${encoder.params.proj_dim}
      pred_dim: 512
      T: 0.1
      num_protos: 512
      num_iters: 3
      topk: 3
      queue_size: 2048


# hydra configuration
experiment: bench

hydra:
  name: ${env}
  run:
    dir: ./exp_local/${now:%Y.%m.%d}/${now:%H%M%S}_${env}_${env_2}_${env_3}_${hydra.job.override_dirname}CRPT
  sweep:
    dir: ./exp/${now:%Y.%m.%d}/${now:%H%M%S}_${experiment}
    subdir: ${hydra.job.num}